SRCS	=	ft_nbrlen.c ft_putnbr_base.c ft_printf.c ft_detect_type.c

MAIN	=	main-test.c

HEADERS	= 	../libft/libft.a ft_printf.h

CC		= 	gcc -Wall -Wextra -Werror

all	:
			$(CC) $(SRCS) $(MAIN) $(HEADERS)
			@echo "Files compiled, run ./a.out to test output"
